---
# tasks file for db_settings

#- name: print the hostname and engineer name
#  debug:
#    msg: "The system hostname is {{ ansible_facts['hostname'] }}. The author is {{ dev.first_name }}  {{ dev.last_name }}"
#
#
#

- name: Configure ulimits for {{ app.username }}
  template:
    src: ../templates/ulimits.conf.j2
    dest: /etc/security/limits.d/{{ app.username }}.conf
    owner: root
    group: root
    mode: '0644'


- name: Ensure 'wheel' group exists
  group:
    name: wheel
    state: present

- name: Create appuser with custom home directory
  user:
    name: "{{ app.username }}"
    home: "{{ app.system_home }}"
    create_home: no
    shell: /bin/bash
    groups: wheel
    append: yes

- name: Ensure home directory exists
  file:
    path: "{{ app.system_home }}"
    state: directory
    owner: "{{ app.username }}"
    group: "{{ app.username }}"
    mode: '0755'

- name: Deploy custom .bashrc from template
  template:
     src: ../templates/bashrc.j2
     dest: "{{ app.system_home }}/.bashrc"
     owner: "{{ app.username }}"
     group: "{{ app.username }}"
     mode: '0644'

- name: Create sudoers file for appuser using Jinja2 template
  template:
    src: ../templates/sudoers.j2
    dest: /etc/sudoers.d/{{ app.username }}
    owner: root
    group: root
    mode: '0440'
    validate: 'visudo -cf %s'

